// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © exlux99

//@version=4
strategy("BB, RSI and ADX Trading System (Seb)", initial_capital=10000, overlay=true)


timeinrange(res, sess) => time(res, sess) != 0


timer = color.red

tpPctInput = input(title='TakeProfit %', defval=0.8, group='Trade Settings')
slPctInput = input(title='StopLoss %', defval=0.8, group='Trade Settings')


//bgcolor(timeinrange(timeframe.period, "0300-0600") or timeinrange(timeframe.period, "0900-1300") or timeinrange(timeframe.period, "2030-2300") ? timer : na, transp=70)


//RSI
length = input( 20 )
overSold = input( 35 )
overBought = input( 65 )
price = close
vrsi = rsi(price, length)
co = crossover(vrsi, overSold)
cu = crossunder(vrsi, overBought)
//if (not na(vrsi))


//BB
lengthB = input(60, minval=1)
src = input(close, title="Source")
mult = input(2.0, minval=0.001, maxval=50, title="StdDev")
basis = sma(src, lengthB)
dev = mult * stdev(src, lengthB)
upper = basis + dev
lower = basis - dev

plot(basis, title='BB Basis', color=color.gray)
plot(upper, title='BB Upper', color=color.aqua)
plot(lower, title='BB Lower', color=color.aqua)


//adx
adxlen = input(14, title="ADX Smoothing")
dilen = input(14, title="DI Length")
dirmov(len) =>
	up = change(high)
	down = -change(low)
	plusDM = na(up) ? na : (up > down and up > 0 ? up : 0)
	minusDM = na(down) ? na : (down > up and down > 0 ? down : 0)
	truerange = rma(tr, len)
	plus = fixnan(100 * rma(plusDM, len) / truerange)
	minus = fixnan(100 * rma(minusDM, len) / truerange)
	[plus, minus]
adx(dilen, adxlen) =>
	[plus, minus] = dirmov(dilen)
	sum = plus + minus
	adx = 100 * rma(abs(plus - minus) / (sum == 0 ? 1 : sum), adxlen)
sig = adx(dilen, adxlen)

longEntry = strategy.position_size == 0 and close < upper and crossover(vrsi, overSold) and sig < 32 //and (timeinrange(timeframe.period, "0301-0600") or timeinrange(timeframe.period, "0901-1300") or timeinrange(timeframe.period, "2031-2300"))

shortEntry = strategy.position_size == 0 and close > upper and crossunder(vrsi,overBought) and sig < 32 //and (timeinrange(timeframe.period, "0301-0600") or timeinrange(timeframe.period, "0901-1300") or timeinrange(timeframe.period, "2031-2300"))


// tp=input(90, step=10)
// sl=input(90, step=10)

// Calculate size of trade
tradeQty = strategy.equity / close

//TP & SLlongEntry
float longTPAmount = na
float longSLAmount = na
float shortTPAmount = na
float shortSLAmount = na
float entryAmount = na
longTPAmount := longEntry ? close + (close * tpPctInput / 100): longTPAmount[1]
longSLAmount := longEntry ? close - (close * slPctInput / 100): longSLAmount[1]
shortTPAmount := shortEntry ? close - (close * tpPctInput / 100): shortTPAmount[1]
shortSLAmount := shortEntry ? close + (close * slPctInput / 100): shortSLAmount[1]
entryAmount := longEntry or shortEntry ? close: entryAmount[1]

plotchar(longTPAmount, "longTPAmount", "", location.top, size = size.tiny)
plotchar(longSLAmount, "longSLAmount", "", location.top, size = size.tiny)
plotchar(shortTPAmount, "shortTPAmount", "", location.top, size = size.tiny)
plotchar(shortSLAmount, "shortSLAmount", "", location.top, size = size.tiny)

// Trade Exits
strategy.exit("LongExit", "LongEntry", qty_percent=100, limit=longTPAmount, stop=longSLAmount)
strategy.exit("ShortExit", "ShortEntry", qty_percent=100, limit=shortTPAmount, stop=shortSLAmount)
// strategy.exit("LongExit", "LongEntry", profit=tp, loss=sl)
// strategy.exit("ShortExit", "ShortEntry", profit=tp, loss=sl)

strategy.close("long",when=crossunder(close,basis))
strategy.close("short",when=crossover(close,basis))

// Trade Entries
strategy.entry("LongEntry", strategy.long, qty=tradeQty, when=longEntry)
strategy.entry("ShortEntry", strategy.short, qty=tradeQty, when=shortEntry)


// Plot trade boxes to show tp/sl zones in reg/green
// We are using (strategy.position_size[1] == 0) to draw for an extra candle, up to the closing candle
zeroLinePlot = plot(strategy.position_size == 0 and strategy.position_size[1] == 0 ? na : entryAmount, color=color.gray, style=plot.style_linebr, linewidth=1)

longSLPlot = plot(strategy.position_size <= 0 and strategy.position_size[1] <= 0 ? na : longSLAmount, color=color.red, style=plot.style_linebr, linewidth=1)
longTPPlot = plot(strategy.position_size <= 0 and strategy.position_size[1] <= 0 ? na : longTPAmount, color=color.green, style=plot.style_linebr, linewidth=1)
fill(zeroLinePlot, longSLPlot, color=color.new(color.red, 90))
fill(zeroLinePlot, longTPPlot, color=color.new(color.green, 90))

shortSLPlot = plot(strategy.position_size >= 0 and strategy.position_size[1] >= 0 ? na : shortSLAmount, color=color.red, style=plot.style_linebr, linewidth=1)
shortTPPlot = plot(strategy.position_size >= 0 and strategy.position_size[1] >= 0 ? na : shortTPAmount, color=color.green, style=plot.style_linebr, linewidth=1)
fill(zeroLinePlot, shortSLPlot, color=color.new(color.red, 90))
fill(zeroLinePlot, shortTPPlot, color=color.new(color.green, 90))
